# Generated by Django 5.2.17 on 2026-09-19 08:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(blank=True, max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short description of the expenditure", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("vendor_name", models.CharField(blank=True, max_length=150)),
                (
                    "quotation_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "quotation_file",
                    models.FileField(
                        blank=True, null=True, upload_to="quotations/%Y/%m/"
                    ),
                ),
                ("currency", models.CharField(default="AED", max_length=10)),
                (
                    "requested_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_L1", "Pending Approver 1"),
                            ("PENDING_L2", "Pending Approver 2"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_L1",
                        max_length=20,
                    ),
                ),
                ("approver1_decision_at", models.DateTimeField(blank=True, null=True)),
                ("approver1_comment", models.CharField(blank=True, max_length=500)),
                ("approver2_decision_at", models.DateTimeField(blank=True, null=True)),
                ("approver2_comment", models.CharField(blank=True, max_length=500)),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="l1_budget_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approver2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="l2_budget_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_requests",
                        to="expenditure.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payee",
                    models.CharField(
                        blank=True, help_text="Vendor / payee name", max_length=150
                    ),
                ),
                ("invoice_reference", models.CharField(blank=True, max_length=100)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=30,
                    ),
                ),
                (
                    "proof_file",
                    models.FileField(
                        blank=True, null=True, upload_to="payment_proofs/%Y/%m/"
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=500)),
                (
                    "requested_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_L1", "Pending Approver 1"),
                            ("PENDING_L2", "Pending Approver 2"),
                            ("APPROVED", "Approved / Released"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_L1",
                        max_length=20,
                    ),
                ),
                ("approver1_decision_at", models.DateTimeField(blank=True, null=True)),
                ("approver1_comment", models.CharField(blank=True, max_length=500)),
                ("approver2_decision_at", models.DateTimeField(blank=True, null=True)),
                ("approver2_comment", models.CharField(blank=True, max_length=500)),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approver1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="l1_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "approver2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="l2_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="expenditure.budgetrequest",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
